### PR TITLE
fix: specify end range indices

### LINKED ISSUE #21: Big big problem in powers_of_ten.rb
`POWERS_RX = Regexp.union(POWERS_OF_TEN.values[1..]).freeze`

Fails because of a syntax error.

 `[1..]` should be `[1..x]` where x is some integer. 

We can't see how you could even run your tests with this in place because ours fail with the syntax error. We've switched back to 0.4.0

### PR DESCRIPTION
**Pull request by markborkum**
Resolves #21

### CODE REVIEW

**Review by markburns — CHANGES_REQUESTED** [review]
Hey only just noticed this. Could you add he ci config back in for the ruby(/ies) that failed without this? 

Then should be good to merge

**Comment by markborkum** [comment]
So far, this PR only modifies the 3 test specs.

Please explain the necessary modifications and I will push a new commit.

**Comment by markburns** [comment]
Hey sorry on mobile and taking a break away from my computer screen so not looking up the exact specifics. But if you can get ci to fail without your changes and then get it to go green with them then that'll do it.
Think this project was on travis. Should be a straightforward edit to probably revert the last change to the config file?

**Comment by markburns** [comment]
Hey thanks for the PR. I've merged in the commit from here and sorted CI out. Looks like it was > 2.5.8 (maybe 2.6.x?) for which the new syntax works, but as per this PR I've removed that support and added in 2.4 and 2.5 as rubies on CI

Your changes are now released in 1.0.0 and from here on out I'll be doing ordinary semver

**Pull request merged**
