### PR TITLE
crude fraction support

### PR DESCRIPTION
**Pull request by trak3r**
not quite comprehensive, but it's test covered and passes and satisfies my personal needs.

### CODE REVIEW

**Comment by markburns** [comment]
I'll use this as a starting point if I implement fractions

**Comment by dimidd** [comment]
I've merged trak3r's work in branch `fractions`. Mark, can you review it?

**Comment by markburns** [comment]
@dimidd can you do as a PR? I'm on mobile and can't seem to do it

**Comment by dimidd** [comment]
Sure, created.

2016-01-28 14:54 GMT+02:00 Mark Burns <notifications@github.com>:

**Pull request closed without merging**
